### ISSUE TITLE
mpld3 library modules not found

### ISSUE THREAD

**Issue by matthewlouismueller** [dpholmes/MechanicalEngineeringLabs-BU#13]
Hello. I was trying to go through some of these exercises and it seems that the mpld3 library is missing the pandas and skimage modules. I looked through the library, but am unsure what the modules have been replaced with.

**Comment by lsmontal** [comment]
Hi @matthewlouismueller, which exercise(s) are you having trouble with? Lab3_MoreBending.ipynb currently runs as expected for me in Anaconda and Colab (mpld3 works fine with pandas and skimage.) Could you clarify the problem with sample input/output?

**Comment by matthewlouismueller** [comment]
In the JupyterIntro, when I try to run the "install_mpld3" block, I get the following response
`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-2fc641680d1b> in <module>
      3 import matplotlib.pyplot as plt   # for plotting
      4 import numpy as np                # for arrays
----> 5 import pandas as pd               # for data/tables
      6 from skimage import io            # working with images
      7 from IPython.display import Image,display # images in colab

ModuleNotFoundError: No module named 'pandas'`

**Comment by lsmontal** [comment]
Thanks for clarifying @matthewlouismueller. You might not have pandas installed (or maybe you have multiple Python distributions). [This](https://github.com/pandas-dev/pandas/issues/11604) thread might help.
